manifest:
  defaults:
    revision: v0.2
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  #  - name: mctechnology17
  #   url-base: https://github.com/mctechnology17
    - name: zmk-nice-oled-zz
      url-base: https://github.com/zzuse/zmk-nice-oled-zz
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
   # - name: zmk-nice-oled
   #   remote: mctechnology17
   #   revision: main
    - name: zmk-nice-oled-zz
      revision: main
      
  self:
    path: config
    